name: vaultify
description: "A secure and efficient local storage solution for Flutter applications."
version: 1.3.1
repository: "https://github.com/Aniketkhote/vaultify"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  refreshed: ^2.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null
