name: vaultify
description: "A secure and efficient local storage solution for Flutter applications."
version: 1.2.0
repository: "https://github.com/Aniketkhote/vaultify"

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  refreshed: ^2.5.7

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter: null
