name: vaultify
description: "A new Flutter package project."
version: 1.0.0
homepage: null

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  refreshed: ^1.4.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter: null
