name: vaultify
description: "A secure and efficient local storage solution for Flutter applications."
version: 1.1.1
repository: "https://github.com/Aniketkhote/vaultify"

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  refreshed: ^1.5.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter: null
