name: vaultify
description: "A secure and efficient local storage solution for Flutter applications."
version: 2.0.1
repository: "https://github.com/Aniketkhote/vaultify"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  refreshed: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null
